version: '3.4'

services:
    catalogdb:
        image: mongo

    graphql.api:
        image: ${DOCKER_REGISTRY-}graphqlapi
        build:
            context: .
            dockerfile: src/GraphQL.API/Dockerfile